[package]
name = "problem_05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tokio = { version = "1.25", features = ["full"]}
regex = "1.7.1"
lazy_static = "1.4.0"